<a href="https://colab.research.google.com/github/isaacsemerson/deeplearning-python-fchollet/blob/main/fchollet_chapter3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
x = tf.ones(shape=(2, 1))
print("tf.ones =", x)

x = tf.zeros(shape=(2,1))
print("tf.ones =", x)

tf.ones = tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.ones = tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


Listing 3.1 - This shows how to create tensors with an initial value set of either 1's or 0's.

In [ ]:
x = tf.random.normal(shape=(3,1), mean=0, stddev=1)
print("Random distribution with a mean of 1:", x)

Random distribution with a mean of 1: tf.Tensor(
[[ 0.12774196]
 [ 1.1695731 ]
 [-0.4984437 ]], shape=(3, 1), dtype=float32)


Listing 3.2 - Creating tensor with initial values averaging around 0. Standard deviation is set to one, which means that most values will be very close to 0.

In [ ]:
x = tf.random.uniform(shape=(3, 1), minval=0, maxval=1)
print("Uniform distribution between 0 and 1:", x)

Uniform distribution between 0 and 1: tf.Tensor(
[[0.13451827]
 [0.8389317 ]
 [0.75061595]], shape=(3, 1), dtype=float32)


Listing 3.2 - Creating tensor with initial values sticking between 0 and 1 (uniform deviation).

In [ ]:
import numpy as np
x = np.ones(shape=(2,2))
print("tensor created with ones", x)
x[0,0] = 0
print("tensor after assigning first value to 0", x)

tensor created with ones [[1. 1.]
 [1. 1.]]
tensor after assigning first value to 0 [[0. 1.]
 [1. 1.]]


Listing 3.3 - Switching to numpy. Key point here is that numpy arrays are assignable after the initial call. I should also format scalars as "0." from now on it seems.

In [5]:
x = tf.ones(shape=(2, 2))
x[0, 0] = 0.

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

Listing 3.4 - This does not work. Point being that tensorflow tensors do not support assignment after the initial call. BUUUT you can use tf.Variables (shown below).

In [ ]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print("Tensorflow variable:", v)

Tensorflow variable: <tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.04123471],
       [-0.32746014],
       [ 0.05621161]], dtype=float32)>


Listing 3.5 - Tensorflow variables! This is how we manage/modify state in tensorflow. Apparently you need to provide a tensor as an initial value.

I believe that tf uses variables as a performance improvement for when it comes to calculating gradient and knowing which variables to track?

In [ ]:
v.assign(tf.ones((3, 1)))
print("Tensorflow variable after being modified:", v)

Tensorflow variable after being modified: <tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


Listing 3.6 - This is how you modify a tensorflow variable.

In [ ]:
v[0,0].assign(3.)
print("Tensorflow variable after updating index 0,0 to a new value:", v)

Tensorflow variable after updating index 0,0 to a new value: <tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>


Listing 3.7 - This is how you update a subset of the tensor's coefficients (values).

In [ ]:
v.assign_add(tf.ones((3,1)))
print("Added 1 to each coefficient", v)
v.assign_sub(tf.ones((2,1)))
print("Subtracted 1 from each coefficient matching a (2,1) tensor:", v)

Added 1 to each coefficient <tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[5.],
       [3.],
       [3.]], dtype=float32)>


InvalidArgumentError: {{function_node __wrapped__AssignSubVariableOp_device_/job:localhost/replica:0/task:0/device:GPU:0}} Cannot update variable with shape [3,1] using a Tensor with shape [2,1], shapes must be equal. [Op:AssignSubVariableOp] name: 

Listing 3.8 - assign_add/sub are how you do += or -= operations in tensorflow. Keep in mind that the assignment must represent a tensor of identical shape (the 2,1 assign_sub above does not work, as an example).

In [ ]:
a = tf.ones((2,2))
print("new tensor initiated with ones, shape 2,2:", a)
b = tf.square(a)
print("square the tensor", b)
c = tf.sqrt(a)
print("take the square root of the initial tensor", c)
d = b + c
print("Element-wise addition of square and square root tensors", d)
e = tf.matmul(a, b)
print("Dot product of the initial tensor and squared tensor", e)
e *= d
print("Element-wise multiplication of dot product tensor and addition tensor", e)


new tensor initiated with ones, shape 2,2: tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
square the tensor tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
take the square root of the initial tensor tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
Element-wise addition of square and square root tensors tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
Dot product of the initial tensor and squared tensor tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
Element-wise multiplication of dot product tensor and addition tensor tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


Listing 3.9 - This shows you how to do basic math operations to tensorflow tensors. Dot product is important to learn (matmul).

In [9]:
import tensorflow as tf
input_var = tf.Variable(initial_value=3.)
print("Initial TF variable:", input_var.numpy())
with tf.GradientTape() as tape:
  result = tf.square(input_var)
  print("TF variable squared", result.numpy())

gradient = tape.gradient(result, input_var)
print("Gradient of squared equation", gradient.numpy())

Initial TF variable: 3.0
TF variable squared 9.0
Gradient of squared equation 6.0


Listing 3.10 - GradientTape is a big part of tensorflow. It allows us to track a set of computations and return the gradient of an equation with respect to an input(s). Calculating gradient is important to learn.

In [4]:
import tensorflow as tf
input_const = tf.constant(3.)
print("Initial TF variable:", input_const.numpy())
with tf.GradientTape() as tape:
  tape.watch(input_const)
  result = tf.square(input_const)
  print("TF variable squared:", result.numpy())

gradient = tape.gradient(result, input_const)
print("Gradient of squared equation with respect to constant tensor:", gradient.numpy())

Initial TF variable: 3.0
TF variable squared: 9.0
Gradient of squared equation with respect to constant tensor: 6.0


Listing 3.11 - Same as 3.10 but this shows that you can use tensors other than tf.Variable in a tape, they just have to be watched. By default only "trainable variables" are tracked.


In [ ]:
time = tf.Va